from django.conf.urls import url 
from . import views

urlpatterns = [
    url(r'^$', views.index),
    url(r'^register$', views.register),
    url(r'^login$', views.login),
    url(r'^dashboard$', views.dashboard),
    url(r'^users/new$', views.new),
    url(r'^users/add$', views.add_user),
    url(r'^users/(?P<id>\d+)/add_message$', views.add_message),
    url(r'^message/(?P<id>\d+)/respond$', views.add_message_response),
    url(r'^users/(?P<id>\d+)/show$', views.show, name="show"),
    url(r'^users/edit/(?P<id>\d+)$', views.user_edit),
    url(r'^users/update/(?P<id>\d+)$', views.user_update),
    url(r'^users/(?P<id>\d+)/edit$', views.admin_edit),
    url(r'^users/(?P<id>\d+)/update$', views.admin_update),
    url(r'^users/(?P<id>\d+)/delete$', views.admin_delete),
    url(r'^users/(?P<id>\d+)/destroy$', views.admin_destroy),
    url(r'^logout$', views.logout),

    # desktop site URLS:
    url(r'^vvi-home$', views.vvi_home),
    url(r'^resources$', views.resources),
    url(r'^contact$', views.contact),
    url(r'^find-a-distributor$', views.distributor),
    url(r'^products$', views.all_products),
    url(r'^new-products$', views.new_products),
    url(r'^single-product$', views.single_product),
    url(r'^about$', views.about),
    url(r'^product-customization$', views.customize),
    url(r'^search$', views.search),
    url(r'^product-prices$', views.prod_prices),
    url(r'^product-prices-results$', views.prices_results),
    url(r'^general-information$', views.gen_info),
    url(r'^application-information$', views.gen_info),
    url(r'^technical-documentation$', views.gen_info),

    # CMS site URLS:
    url(r'^cms-home$', views.cms_home),
    url(r'^cms-product-category$', views.cms_prod_cat),
    url(r'^add-product$', views.cms_add_prod),
    url(r'^edit-product$', views.cms_edit_prod),
    url(r'^generate-pdf$', views.cms_gen_pdf),
    url(r'^manage-resources$', views.cms_mng_res),
    url(r'^manage-resource$', views.cms_mng_one_res),
    url(r'^add-resource$', views.cms_add_res),
    url(r'^edit-resources$', views.cms_edit_res),
    url(r'^edit-resource$', views.cms_edit_one_res),
    url(r'^model-pricing$', views.cms_model_price),
    url(r'^download-stp$', views.cms_stp_down),
]