# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-21 21:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_admin_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='admin_level',
            field=models.CharField(max_length=10),
        ),
    ]
