# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-22 13:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20170821_1651'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='user',
            new_name='poster',
        ),
        migrations.AddField(
            model_name='message',
            name='posted_on',
            field=models.IntegerField(default=0),
        ),
    ]
