def primeSquares(num1, num2): 
  for x in range (num1, num2+1): #for all #s between num1 and num2 (+1 includes num2)...
    prime = True 
    square = False 
    for i in range (2, int(x/2)+1): #for every # between 2 and the closest whole # of ((x/2)+1), which accounts for odd #s...
      if (i*i) == x: #...if there are any values of i that, when multplied by itself, are equal to x...
        square = True 
      elif (x % i == 0): #...OR if x can be divided by any value of i...
        prime = False 
    if square or x == 1: #if square is true...
      print 'Bar' 
    elif prime: #or if prime is true and x is not 1...
      print 'Foo' 
    else:
      print 'FooBar' 
      
primeSquares(1,50) 