# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-16 21:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_authors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='note',
            field=models.TextField(default='some_string'),
        ),
    ]
